### ISSUE TITLE
EOS_EVM_SDK Todo

### ISSUE THREAD

**Issue by Frank-AFN** [eosiosg/eos_evm_sdk#3]
1. Get ERC20 balance 
2. Get ERC20 allowance
3. Get ERC20 balance no gas fee
4. Get ERC20 allowance no gas fee

**Comment by qianxiaofeng** [comment]
get native balance
transfer
update sendAction
去掉test cases， 这个版本先不做

**Comment by qianxiaofeng** [comment]
get 方法的细节讨论 #4 @Frank-AFN
