### ISSUE TITLE
关于get_balance等方法不应该发布上链交易的问题

### ISSUE THREAD

**Issue by qianxiaofeng** [eosiosg/eos_evm_sdk#4]
get_balance 等类似方法：
获取余额的实现，是通过evm trx 在evm中执行来获取数据，虽然需要evm执行， 但是本身不应该作为链上执行交易。 而且通过eos trx的方式调用，客户端也无法获取真实余额。

解决方法思路
一：考虑提供特定api的方式来执行evm获取数据， 该api返回evm执行的结果，但是不向外广播交易
二： 通过类似get table的方式获取原始数据， 然后通过web3帮助解析数据

@Frank-AFN review一下问题以及解决思路

**Comment by qianxiaofeng** [comment]
eos代码中 producer_plugin.cpp里
process_incoming_transaction_async 方法
```
 _transaction_ack_channel.publish(priority::low, std::pair<fc::exception_ptr,transaction_metadata_ptr>(nullptr, trx));
```
触发了向外广播trx

**Comment by qianxiaofeng** [comment]
对于思路一：
push transaction调用链为
1. chain_api_plugin 的push transaction
2. proudcer_plugin 的process_incoming_transaction_async
3. controller 的 controller::push_transaction

为了避免改动producer plugin， 需要新增类似 eos_evm_plugin  eos_evm_api_plugin 
抽出controller::push_transaction相关逻辑， 运行下面类似方法          
`auto trace = chain.push_transaction( trx, deadline, trx->billed_cpu_time_us, false );`
获取封装好的evmc result， 作为结果返回， 并保证chain.push_transaction的改动被revert掉

**Comment by qianxiaofeng** [comment]
对于思路二：

不需要改动nodeos代码， 但需要针对 storage的key value格式做对应解析。
可能需要abi支持，如果针对特定demo的话可定制解决。

目前看起来对比思路一更优一些

**Comment by qianxiaofeng** [comment]
@Frank-AFN 思路三关于simulate接口的描述补充一下

**Comment by Frank-AFN** [comment]
思路三, 增加simulate action. 这个action总会assert失败. 目的是从pending console output中获取EVM执行的信息. 用此方法来模拟ETH上 **broadcast=false** 的情况. 
优点: 
1. 用户可以在交易不上链的情况下, 获取到EVM执行的receipt. 如status_code, gas fee, value等. 
2. 可以在交易不上链, 不消耗gas fee的情况下获得信息.  适用于ERC20BalanceOf, ERC20TotalSupply, ERC20Symbol, ERC20Decimals, ERC20Allowance等.

**Comment by qianxiaofeng** [comment]
使用思路三的解决方案
