### ISSUE TITLE
接口优化

### ISSUE THREAD

**Issue by qianxiaofeng** [eosiosg/eos_evm_sdk#5]
1. readme 各个方法的序号更正
2. ERC20 作为demo放在最后作为一个大类，里面的各个方法作为小点， 其他基本功能的接口放在前面
3. 目前的sendAction方法作为一个原始接口
4. 封装新接口 
- transfer
- create contract
- call
5. get native balance接口， 其他ERC20的get接口依赖 #4

**Comment by Frank-AFN** [comment]
已完成 #8
