### ISSUE TITLE
获取evm执行返回的结果

### ISSUE THREAD

**Issue by qianxiaofeng** [eosiosg/eos_evm_sdk#7]
evm执行成功或者失败无法在client端获取结果， 需要有相关功能使用户获得相关信息

**Comment by Frank-AFN** [comment]
![image](https://user-images.githubusercontent.com/12408187/77499854-3a417080-6e8e-11ea-9ef6-d4e0d8f444b4.png)

如果被EOS transaction 被 assert会在 **pending console output:  ** 显示contract print信息

**Comment by Frank-AFN** [comment]
Solution: 

- 在合约中**print** vm receipt as json. 

- 在JS client端 可以从**action_traces**中获取console打印结果. 拿到console print json. 进行解析.
